# Generated by Django 3.1.3 on 2021-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('tagline', models.CharField(default='', max_length=100)),
                ('mrp', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('Discount', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='accounts/img')),
            ],
        ),
    ]
